# Generated by Django 3.1.4 on 2020-12-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_phishing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eragonphish',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='eragonphish',
            name='username',
            field=models.CharField(max_length=500),
        ),
    ]
