# Generated by Django 3.1.4 on 2020-12-13 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_phishing', '0002_auto_20201213_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eragonphish',
            old_name='password',
            new_name='passw',
        ),
        migrations.RenameField(
            model_name='eragonphish',
            old_name='username',
            new_name='user',
        ),
    ]
