# Generated by Django 3.1.4 on 2020-12-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_phishing', '0003_auto_20201213_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDePaginas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
